#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import logging
import os
import sys
import time
import argparse
import traceback
import requests
from typing import Dict, List, Any, Optional, Union
from datetime import datetime
from pathlib import Path

# 导入变异模块
try:
    from vdbfuzz.mutator import Mutator
except ImportError:
    try:
        # 尝试相对导入
        sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        from vdbfuzz.mutator import Mutator
    except ImportError:
        # 尝试从当前目录的父目录导入
        vdbfuzz_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'vdbfuzz')
        if os.path.exists(vdbfuzz_path):
            sys.path.append(os.path.dirname(vdbfuzz_path))
            from vdbfuzz.mutator import Mutator
        else:
            # 如果还是找不到，定义一个最小的Mutator类
            class Mutator:
                @staticmethod
                def generate_float_array(dimension, normalized=False, min_val=-1.0, max_val=1.0):
                    import random, math
                    array = [random.uniform(min_val, max_val) for _ in range(dimension)]
                    if normalized and array:
                        length = math.sqrt(sum(x*x for x in array))
                        if length > 0:
                            array = [x/length for x in array]
                    return array
                    
                @staticmethod
                def generate_embedding_matrix(rows, embedding_dim, normalized=True):
                    return [Mutator.generate_float_array(embedding_dim, normalized) for _ in range(rows)]
                    
                @staticmethod
                def generate_multi_dim_array(dimensions, normalized=False, min_val=-1.0, max_val=1.0):
                    if not dimensions:
                        return []
                    if len(dimensions) == 1:
                        return Mutator.generate_float_array(dimensions[0], normalized, min_val, max_val)
                    
                    result = []
                    for _ in range(dimensions[0]):
                        if len(dimensions) == 2:
                            result.append(Mutator.generate_float_array(dimensions[1], normalized, min_val, max_val))
                        else:
                            result.append(Mutator.generate_multi_dim_array(dimensions[1:], normalized, min_val, max_val))
                    return result
                    
                def normal_mutate(self, original_content, send_request, connectivity_check_func, save_failure_func=None, max_iterations=200, **kwargs):
                    # 简化版本，只返回空列表
                    logger.info("开始随机变异测试，最大测试次数: 200")
                    return []



# 日志配置
# 创建目录存放日志文件
os.makedirs('logs', exist_ok=True)

# 添加控制台处理器
console_handler = logging.StreamHandler()
console_handler.setLevel(logging.INFO)
console_formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console_handler.setFormatter(console_formatter)

# 添加文件处理器
# 使用时间戳作为文件名的一部分
log_file = "logs/mutation_test_" + datetime.now().strftime('%Y%m%d_%H%M%S') + ".log"
file_handler = logging.FileHandler(log_file, encoding='utf-8')
file_handler.setLevel(logging.DEBUG)  # 文件中记录详细日志
file_formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
file_handler.setFormatter(file_formatter)

# 配置根日志器
root_logger = logging.getLogger()
root_logger.setLevel(logging.DEBUG)  # 设置为DEBUG级别以捕获所有日志
root_logger.addHandler(console_handler)
root_logger.addHandler(file_handler)


# 获取测试模块的日志器
logger = logging.getLogger('vdbfuzz.test.allmilvus_log_TestRestfulSdkCompatibility_test_collection_create_by_sdk_insert_vector_by_restful_1752747033_json')
logger.info("日志文件将输出到: " + log_file)

# 全局变量
TARGET_URL = ""
OUTPUT_DIR = "templates_milvus"
TEST_NAME = "allmilvus_log.TestRestfulSdkCompatibility_test_collection_create_by_sdk_insert_vector_by_restful_1752747033.json"
VDB_TYPE = "milvus"


def send_request(content, request_type="POST", url_path="http://172.17.0.5:23210/v2/vectordb/entities/insert", custom_headers=None):
    """
    发送请求到目标服务器

    Args:
        content: 请求内容
        request_type: 请求方法，默认为"POST"
        url_path: URL路径，默认为"http://172.17.0.5:23210/v2/vectordb/entities/insert"
        custom_headers: 自定义请求头，如果提供则会合并到默认headers
        
    Returns:
        requests.Response: 响应对象
    """
    if not TARGET_URL:
        raise ValueError("目标URL未设置，请使用 -t 参数指定目标服务器URL")
    
    # 检查url_path是否已经是完整URL
    if url_path.startswith(('http://', 'https://')):
        from urllib.parse import urlsplit

        parsed = urlsplit(url_path)
        path = parsed.path or '/'
        if parsed.query:
            path = f"{path}?{parsed.query}"
        url = TARGET_URL.rstrip('/') + path
    else:
        url = TARGET_URL.rstrip('/') + url_path
    
    # 基础请求头
    headers = {
        'Content-Type': 'application/json',
    }

    # 合并自定义请求头
    if custom_headers:
        headers.update(custom_headers)

    try:
        logger.debug(f"发送 {request_type} 请求到 {url}")
        if request_type in ['POST', 'PUT']:
            response = requests.request(
                method=request_type,
                url=url,
                headers=headers,
                json=content,
                timeout=10
            )
        else:
            response = requests.request(
                method=request_type,
                url=url,
                headers=headers,
                params=content,
                timeout=10
            )
        
        # 打印请求结果摘要
        logger.info(f"请求响应状态码: {response.status_code}")
        
        return response
    except Exception as e:
        logger.error(f"发送请求失败: {str(e)}")
        return None



def check_connectivity():
    """
    检查向量数据库连通性

    Returns:
        bool: 数据库是否可连接
    """
    if not TARGET_URL:
        return False

    try:
        url = TARGET_URL.rstrip('/') + "/"
        response = requests.get(url, timeout=5)
        return response.status_code in [200, 404, 503]
    except Exception as e:
        logger.error(f"连通性检查失败: {str(e)}")
        return False



def save_failure(failure_info):
    """
    保存失败信息到文件

    Args:
        failure_info: 失败信息字典
    """
    if not OUTPUT_DIR:
        logger.warning("输出目录未设置，无法保存失败信息")
        return

    # 创建失败信息目录
    failure_dir = Path(OUTPUT_DIR) / "failures" / TEST_NAME.replace(".", "_")
    failure_dir.mkdir(parents=True, exist_ok=True)

    # 生成文件名
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    mutation_type = failure_info.get("mutation", {}).get("type", "unknown")
    mutation_path = "_".join(str(x) for x in failure_info.get("mutation", {}).get("path", []))
    
    filename = f"failure_{mutation_type}_{mutation_path}_{timestamp}.json"
    file_path = failure_dir / filename
    
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(failure_info, f, indent=2, ensure_ascii=False)
        logger.info(f"已保存失败信息到 {file_path}")
    except Exception as e:
        logger.error(f"保存失败信息失败: {str(e)}")



class AllmilvusLogtestrestfulsdkcompatibilityTestCollectionCreateBySdkInsertVectorByRestful1752747033Json:
    """自动生成的VDB模糊测试类 - allmilvus_log.TestRestfulSdkCompatibility_test_collection_create_by_sdk_insert_vector_by_restful_1752747033.json"""
    
    def __init__(self):
        """初始化测试类"""
        self.test_name = "allmilvus_log.TestRestfulSdkCompatibility_test_collection_create_by_sdk_insert_vector_by_restful_1752747033.json"
        self.test_count = 3  # 测试方法数量
        self.mutator = Mutator()  # 初始化变异器
    
    def run_tests(self):
        """运行所有测试"""
        logger.info(f"开始测试: {self.test_name}")
        logger.info(f"目标URL: {TARGET_URL}")
        
        # 检查连通性
        if not check_connectivity():
            logger.error("无法连接到目标服务器，测试终止")
            return False
        
        # 运行所有测试用例
        try:
            for i in range(self.test_count):
                logger.info(f"运行测试 {i+1}/{self.test_count}")
                method_name = f"test_request_{i}"
                if hasattr(self, method_name):
                    test_method = getattr(self, method_name)
                    test_method()
                else:
                    logger.warning(f"未找到测试方法: {method_name}")
            
            logger.info("所有测试完成")
            return True
        except Exception as e:
            logger.error(f"测试过程中发生异常: {str(e)}")
            traceback.print_exc()
            return False


    def test_request_0(self):
        """测试请求 0 - POST http://172.17.0.5:23210/v2/vectordb/entities/insert"""
        logger.info(f"跳过非写请求或无内容请求: POST http://172.17.0.5:23210/v2/vectordb/entities/insert")
        method = 'POST'
        url_path = 'http://172.17.0.5:23210/v2/vectordb/entities/insert'
        headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer None',
    'Accept-Type-Allow-Int64': 'true',
    'RequestId': '45acd4a2-62f6-11f0-91de-0242ac11000b',
    'Request-Timeout': '120',
}
        
        # 原始请求内容
        original_content = {
    'collectionName': 'test_collection_2025_07_17_18_10_31_895086KEnvmmyf',
    'data': [
    {
    'int64': 0,
    'float': 0,
    'varchar': '0',
    'json': {
    'key_0': 'value_0',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 0,
},
    {
    'int64': 1,
    'float': 1,
    'varchar': '1',
    'json': {
    'key_1': 'value_1',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 1,
},
    {
    'int64': 2,
    'float': 2,
    'varchar': '2',
    'json': {
    'key_2': 'value_2',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 2,
},
    {
    'int64': 3,
    'float': 3,
    'varchar': '3',
    'json': {
    'key_3': 'value_3',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 3,
},
    {
    'int64': 4,
    'float': 4,
    'varchar': '4',
    'json': {
    'key_4': 'value_4',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 4,
},
    {
    'int64': 5,
    'float': 5,
    'varchar': '5',
    'json': {
    'key_5': 'value_5',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 5,
},
    {
    'int64': 6,
    'float': 6,
    'varchar': '6',
    'json': {
    'key_6': 'value_6',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 6,
},
    {
    'int64': 7,
    'float': 7,
    'varchar': '7',
    'json': {
    'key_7': 'value_7',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 7,
},
    {
    'int64': 8,
    'float': 8,
    'varchar': '8',
    'json': {
    'key_8': 'value_8',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 8,
},
    {
    'int64': 9,
    'float': 9,
    'varchar': '9',
    'json': {
    'key_9': 'value_9',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 9,
},
    {
    'int64': 10,
    'float': 10,
    'varchar': '10',
    'json': {
    'key_10': 'value_10',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 10,
},
    {
    'int64': 11,
    'float': 11,
    'varchar': '11',
    'json': {
    'key_11': 'value_11',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 11,
},
    {
    'int64': 12,
    'float': 12,
    'varchar': '12',
    'json': {
    'key_12': 'value_12',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 12,
},
    {
    'int64': 13,
    'float': 13,
    'varchar': '13',
    'json': {
    'key_13': 'value_13',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 13,
},
    {
    'int64': 14,
    'float': 14,
    'varchar': '14',
    'json': {
    'key_14': 'value_14',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 14,
},
    {
    'int64': 15,
    'float': 15,
    'varchar': '15',
    'json': {
    'key_15': 'value_15',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 15,
},
    {
    'int64': 16,
    'float': 16,
    'varchar': '16',
    'json': {
    'key_16': 'value_16',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 16,
},
    {
    'int64': 17,
    'float': 17,
    'varchar': '17',
    'json': {
    'key_17': 'value_17',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 17,
},
    {
    'int64': 18,
    'float': 18,
    'varchar': '18',
    'json': {
    'key_18': 'value_18',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 18,
},
    {
    'int64': 19,
    'float': 19,
    'varchar': '19',
    'json': {
    'key_19': 'value_19',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 19,
},
    {
    'int64': 20,
    'float': 20,
    'varchar': '20',
    'json': {
    'key_20': 'value_20',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 20,
},
    {
    'int64': 21,
    'float': 21,
    'varchar': '21',
    'json': {
    'key_21': 'value_21',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 21,
},
    {
    'int64': 22,
    'float': 22,
    'varchar': '22',
    'json': {
    'key_22': 'value_22',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 22,
},
    {
    'int64': 23,
    'float': 23,
    'varchar': '23',
    'json': {
    'key_23': 'value_23',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 23,
},
    {
    'int64': 24,
    'float': 24,
    'varchar': '24',
    'json': {
    'key_24': 'value_24',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 24,
},
    {
    'int64': 25,
    'float': 25,
    'varchar': '25',
    'json': {
    'key_25': 'value_25',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 25,
},
    {
    'int64': 26,
    'float': 26,
    'varchar': '26',
    'json': {
    'key_26': 'value_26',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 26,
},
    {
    'int64': 27,
    'float': 27,
    'varchar': '27',
    'json': {
    'key_27': 'value_27',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 27,
},
    {
    'int64': 28,
    'float': 28,
    'varchar': '28',
    'json': {
    'key_28': 'value_28',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 28,
},
    {
    'int64': 29,
    'float': 29,
    'varchar': '29',
    'json': {
    'key_29': 'value_29',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 29,
},
    {
    'int64': 30,
    'float': 30,
    'varchar': '30',
    'json': {
    'key_30': 'value_30',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 30,
},
    {
    'int64': 31,
    'float': 31,
    'varchar': '31',
    'json': {
    'key_31': 'value_31',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 31,
},
    {
    'int64': 32,
    'float': 32,
    'varchar': '32',
    'json': {
    'key_32': 'value_32',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 32,
},
    {
    'int64': 33,
    'float': 33,
    'varchar': '33',
    'json': {
    'key_33': 'value_33',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 33,
},
    {
    'int64': 34,
    'float': 34,
    'varchar': '34',
    'json': {
    'key_34': 'value_34',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 34,
},
    {
    'int64': 35,
    'float': 35,
    'varchar': '35',
    'json': {
    'key_35': 'value_35',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 35,
},
    {
    'int64': 36,
    'float': 36,
    'varchar': '36',
    'json': {
    'key_36': 'value_36',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 36,
},
    {
    'int64': 37,
    'float': 37,
    'varchar': '37',
    'json': {
    'key_37': 'value_37',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 37,
},
    {
    'int64': 38,
    'float': 38,
    'varchar': '38',
    'json': {
    'key_38': 'value_38',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 38,
},
    {
    'int64': 39,
    'float': 39,
    'varchar': '39',
    'json': {
    'key_39': 'value_39',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 39,
},
    {
    'int64': 40,
    'float': 40,
    'varchar': '40',
    'json': {
    'key_40': 'value_40',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 40,
},
    {
    'int64': 41,
    'float': 41,
    'varchar': '41',
    'json': {
    'key_41': 'value_41',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 41,
},
    {
    'int64': 42,
    'float': 42,
    'varchar': '42',
    'json': {
    'key_42': 'value_42',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 42,
},
    {
    'int64': 43,
    'float': 43,
    'varchar': '43',
    'json': {
    'key_43': 'value_43',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 43,
},
    {
    'int64': 44,
    'float': 44,
    'varchar': '44',
    'json': {
    'key_44': 'value_44',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 44,
},
    {
    'int64': 45,
    'float': 45,
    'varchar': '45',
    'json': {
    'key_45': 'value_45',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 45,
},
    {
    'int64': 46,
    'float': 46,
    'varchar': '46',
    'json': {
    'key_46': 'value_46',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 46,
},
    {
    'int64': 47,
    'float': 47,
    'varchar': '47',
    'json': {
    'key_47': 'value_47',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 47,
},
    {
    'int64': 48,
    'float': 48,
    'varchar': '48',
    'json': {
    'key_48': 'value_48',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 48,
},
    {
    'int64': 49,
    'float': 49,
    'varchar': '49',
    'json': {
    'key_49': 'value_49',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 49,
},
    {
    'int64': 50,
    'float': 50,
    'varchar': '50',
    'json': {
    'key_50': 'value_50',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 50,
},
    {
    'int64': 51,
    'float': 51,
    'varchar': '51',
    'json': {
    'key_51': 'value_51',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 51,
},
    {
    'int64': 52,
    'float': 52,
    'varchar': '52',
    'json': {
    'key_52': 'value_52',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 52,
},
    {
    'int64': 53,
    'float': 53,
    'varchar': '53',
    'json': {
    'key_53': 'value_53',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 53,
},
    {
    'int64': 54,
    'float': 54,
    'varchar': '54',
    'json': {
    'key_54': 'value_54',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 54,
},
    {
    'int64': 55,
    'float': 55,
    'varchar': '55',
    'json': {
    'key_55': 'value_55',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 55,
},
    {
    'int64': 56,
    'float': 56,
    'varchar': '56',
    'json': {
    'key_56': 'value_56',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 56,
},
    {
    'int64': 57,
    'float': 57,
    'varchar': '57',
    'json': {
    'key_57': 'value_57',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 57,
},
    {
    'int64': 58,
    'float': 58,
    'varchar': '58',
    'json': {
    'key_58': 'value_58',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 58,
},
    {
    'int64': 59,
    'float': 59,
    'varchar': '59',
    'json': {
    'key_59': 'value_59',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 59,
},
    {
    'int64': 60,
    'float': 60,
    'varchar': '60',
    'json': {
    'key_60': 'value_60',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 60,
},
    {
    'int64': 61,
    'float': 61,
    'varchar': '61',
    'json': {
    'key_61': 'value_61',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 61,
},
    {
    'int64': 62,
    'float': 62,
    'varchar': '62',
    'json': {
    'key_62': 'value_62',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 62,
},
    {
    'int64': 63,
    'float': 63,
    'varchar': '63',
    'json': {
    'key_63': 'value_63',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 63,
},
    {
    'int64': 64,
    'float': 64,
    'varchar': '64',
    'json': {
    'key_64': 'value_64',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 64,
},
    {
    'int64': 65,
    'float': 65,
    'varchar': '65',
    'json': {
    'key_65': 'value_65',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 65,
},
    {
    'int64': 66,
    'float': 66,
    'varchar': '66',
    'json': {
    'key_66': 'value_66',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 66,
},
    {
    'int64': 67,
    'float': 67,
    'varchar': '67',
    'json': {
    'key_67': 'value_67',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 67,
},
    {
    'int64': 68,
    'float': 68,
    'varchar': '68',
    'json': {
    'key_68': 'value_68',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 68,
},
    {
    'int64': 69,
    'float': 69,
    'varchar': '69',
    'json': {
    'key_69': 'value_69',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 69,
},
    {
    'int64': 70,
    'float': 70,
    'varchar': '70',
    'json': {
    'key_70': 'value_70',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 70,
},
    {
    'int64': 71,
    'float': 71,
    'varchar': '71',
    'json': {
    'key_71': 'value_71',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 71,
},
    {
    'int64': 72,
    'float': 72,
    'varchar': '72',
    'json': {
    'key_72': 'value_72',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 72,
},
    {
    'int64': 73,
    'float': 73,
    'varchar': '73',
    'json': {
    'key_73': 'value_73',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 73,
},
    {
    'int64': 74,
    'float': 74,
    'varchar': '74',
    'json': {
    'key_74': 'value_74',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 74,
},
    {
    'int64': 75,
    'float': 75,
    'varchar': '75',
    'json': {
    'key_75': 'value_75',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 75,
},
    {
    'int64': 76,
    'float': 76,
    'varchar': '76',
    'json': {
    'key_76': 'value_76',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 76,
},
    {
    'int64': 77,
    'float': 77,
    'varchar': '77',
    'json': {
    'key_77': 'value_77',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 77,
},
    {
    'int64': 78,
    'float': 78,
    'varchar': '78',
    'json': {
    'key_78': 'value_78',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 78,
},
    {
    'int64': 79,
    'float': 79,
    'varchar': '79',
    'json': {
    'key_79': 'value_79',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 79,
},
    {
    'int64': 80,
    'float': 80,
    'varchar': '80',
    'json': {
    'key_80': 'value_80',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 80,
},
    {
    'int64': 81,
    'float': 81,
    'varchar': '81',
    'json': {
    'key_81': 'value_81',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 81,
},
    {
    'int64': 82,
    'float': 82,
    'varchar': '82',
    'json': {
    'key_82': 'value_82',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 82,
},
    {
    'int64': 83,
    'float': 83,
    'varchar': '83',
    'json': {
    'key_83': 'value_83',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 83,
},
    {
    'int64': 84,
    'float': 84,
    'varchar': '84',
    'json': {
    'key_84': 'value_84',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 84,
},
    {
    'int64': 85,
    'float': 85,
    'varchar': '85',
    'json': {
    'key_85': 'value_85',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 85,
},
    {
    'int64': 86,
    'float': 86,
    'varchar': '86',
    'json': {
    'key_86': 'value_86',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 86,
},
    {
    'int64': 87,
    'float': 87,
    'varchar': '87',
    'json': {
    'key_87': 'value_87',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 87,
},
    {
    'int64': 88,
    'float': 88,
    'varchar': '88',
    'json': {
    'key_88': 'value_88',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 88,
},
    {
    'int64': 89,
    'float': 89,
    'varchar': '89',
    'json': {
    'key_89': 'value_89',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 89,
},
    {
    'int64': 90,
    'float': 90,
    'varchar': '90',
    'json': {
    'key_90': 'value_90',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 90,
},
    {
    'int64': 91,
    'float': 91,
    'varchar': '91',
    'json': {
    'key_91': 'value_91',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 91,
},
    {
    'int64': 92,
    'float': 92,
    'varchar': '92',
    'json': {
    'key_92': 'value_92',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 92,
},
    {
    'int64': 93,
    'float': 93,
    'varchar': '93',
    'json': {
    'key_93': 'value_93',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 93,
},
    {
    'int64': 94,
    'float': 94,
    'varchar': '94',
    'json': {
    'key_94': 'value_94',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 94,
},
    {
    'int64': 95,
    'float': 95,
    'varchar': '95',
    'json': {
    'key_95': 'value_95',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 95,
},
    {
    'int64': 96,
    'float': 96,
    'varchar': '96',
    'json': {
    'key_96': 'value_96',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 96,
},
    {
    'int64': 97,
    'float': 97,
    'varchar': '97',
    'json': {
    'key_97': 'value_97',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 97,
},
    {
    'int64': 98,
    'float': 98,
    'varchar': '98',
    'json': {
    'key_98': 'value_98',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 98,
},
    {
    'int64': 99,
    'float': 99,
    'varchar': '99',
    'json': {
    'key_99': 'value_99',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 99,
},
],
}


        send_request(original_content, method, url_path, headers)
        return True



    def test_request_1(self):
        """测试请求 1 - POST http://172.17.0.5:23210/v2/vectordb/collections/list"""
        logger.info(f"测试请求: POST http://172.17.0.5:23210/v2/vectordb/collections/list")
        
        method = 'POST'
        url_path = 'http://172.17.0.5:23210/v2/vectordb/collections/list'
        headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer None',
    'RequestId': '45acd4a2-62f6-11f0-91de-0242ac11000b',
    'Request-Timeout': '120',
}
        
        # 原始请求内容
        original_content = 'null'
        
        if not original_content:
            logger.info("请求无内容，跳过变异测试")
            return True
        
        # 定义发送请求的函数
        def send_mutated_request(mutated_content):
            return send_request(mutated_content, method, url_path, headers)
        
        logger.info("开始变异测试...")
        
        # 获取命令行参数
        iterations = getattr(args, 'iterations', 200)  # 默认值为200
        time_limit = getattr(args, 'time_limit', 10)   # 默认值为10分钟
                    
        mutator = Mutator()  # 创建变异器实例
        failures = mutator.normal_mutate(
            original_content=original_content,
            send_request=send_mutated_request,
            connectivity_check_func=check_connectivity,
            save_failure_func=save_failure,
            max_time_minutes=time_limit,  # 使用上面设置的time_limit变量
            max_iterations=iterations     # 使用上面设置的iterations变量
        )
        
        if failures:
            logger.warning(f"发现 {len(failures)} 个导致异常的变异")
        else:
            logger.info("变异测试未发现异常")
        
        return len(failures) == 0



    def test_request_2(self):
        """测试请求 2 - DELETE http://172.17.0.5:23210/v2/vectordb/entities/insert"""
        logger.info(f"跳过非写请求或无内容请求: DELETE http://172.17.0.5:23210/v2/vectordb/entities/insert")
        method = 'DELETE'
        url_path = 'http://172.17.0.5:23210/v2/vectordb/entities/insert'
        headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer None',
    'Accept-Type-Allow-Int64': 'true',
    'RequestId': '45acd4a2-62f6-11f0-91de-0242ac11000b',
    'Request-Timeout': '120',
}
        
        # 原始请求内容
        original_content = {
    'collectionName': 'test_collection_2025_07_17_18_10_31_895086KEnvmmyf',
    'data': [
    {
    'int64': 0,
    'float': 0,
    'varchar': '0',
    'json': {
    'key_0': 'value_0',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 0,
},
    {
    'int64': 1,
    'float': 1,
    'varchar': '1',
    'json': {
    'key_1': 'value_1',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 1,
},
    {
    'int64': 2,
    'float': 2,
    'varchar': '2',
    'json': {
    'key_2': 'value_2',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
    '2',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 2,
},
    {
    'int64': 3,
    'float': 3,
    'varchar': '3',
    'json': {
    'key_3': 'value_3',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
    '3',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 3,
},
    {
    'int64': 4,
    'float': 4,
    'varchar': '4',
    'json': {
    'key_4': 'value_4',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
    '4',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 4,
},
    {
    'int64': 5,
    'float': 5,
    'varchar': '5',
    'json': {
    'key_5': 'value_5',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
    '5',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 5,
},
    {
    'int64': 6,
    'float': 6,
    'varchar': '6',
    'json': {
    'key_6': 'value_6',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
    '6',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 6,
},
    {
    'int64': 7,
    'float': 7,
    'varchar': '7',
    'json': {
    'key_7': 'value_7',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
    '7',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 7,
},
    {
    'int64': 8,
    'float': 8,
    'varchar': '8',
    'json': {
    'key_8': 'value_8',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
    '8',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 8,
},
    {
    'int64': 9,
    'float': 9,
    'varchar': '9',
    'json': {
    'key_9': 'value_9',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
    '9',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 9,
},
    {
    'int64': 10,
    'float': 10,
    'varchar': '10',
    'json': {
    'key_10': 'value_10',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 10,
},
    {
    'int64': 11,
    'float': 11,
    'varchar': '11',
    'json': {
    'key_11': 'value_11',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
    '11',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 11,
},
    {
    'int64': 12,
    'float': 12,
    'varchar': '12',
    'json': {
    'key_12': 'value_12',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
    '12',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 12,
},
    {
    'int64': 13,
    'float': 13,
    'varchar': '13',
    'json': {
    'key_13': 'value_13',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
    '13',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 13,
},
    {
    'int64': 14,
    'float': 14,
    'varchar': '14',
    'json': {
    'key_14': 'value_14',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
    '14',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 14,
},
    {
    'int64': 15,
    'float': 15,
    'varchar': '15',
    'json': {
    'key_15': 'value_15',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
    '15',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 15,
},
    {
    'int64': 16,
    'float': 16,
    'varchar': '16',
    'json': {
    'key_16': 'value_16',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
    '16',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 16,
},
    {
    'int64': 17,
    'float': 17,
    'varchar': '17',
    'json': {
    'key_17': 'value_17',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
    '17',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 17,
},
    {
    'int64': 18,
    'float': 18,
    'varchar': '18',
    'json': {
    'key_18': 'value_18',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
    '18',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 18,
},
    {
    'int64': 19,
    'float': 19,
    'varchar': '19',
    'json': {
    'key_19': 'value_19',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
    '19',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 19,
},
    {
    'int64': 20,
    'float': 20,
    'varchar': '20',
    'json': {
    'key_20': 'value_20',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
    '20',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 20,
},
    {
    'int64': 21,
    'float': 21,
    'varchar': '21',
    'json': {
    'key_21': 'value_21',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
    '21',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 21,
},
    {
    'int64': 22,
    'float': 22,
    'varchar': '22',
    'json': {
    'key_22': 'value_22',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
    '22',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 22,
},
    {
    'int64': 23,
    'float': 23,
    'varchar': '23',
    'json': {
    'key_23': 'value_23',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
    '23',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 23,
},
    {
    'int64': 24,
    'float': 24,
    'varchar': '24',
    'json': {
    'key_24': 'value_24',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
    '24',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 24,
},
    {
    'int64': 25,
    'float': 25,
    'varchar': '25',
    'json': {
    'key_25': 'value_25',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
    '25',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 25,
},
    {
    'int64': 26,
    'float': 26,
    'varchar': '26',
    'json': {
    'key_26': 'value_26',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
    '26',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 26,
},
    {
    'int64': 27,
    'float': 27,
    'varchar': '27',
    'json': {
    'key_27': 'value_27',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
    '27',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 27,
},
    {
    'int64': 28,
    'float': 28,
    'varchar': '28',
    'json': {
    'key_28': 'value_28',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
    '28',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 28,
},
    {
    'int64': 29,
    'float': 29,
    'varchar': '29',
    'json': {
    'key_29': 'value_29',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
    '29',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 29,
},
    {
    'int64': 30,
    'float': 30,
    'varchar': '30',
    'json': {
    'key_30': 'value_30',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
    '30',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 30,
},
    {
    'int64': 31,
    'float': 31,
    'varchar': '31',
    'json': {
    'key_31': 'value_31',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
    '31',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 31,
},
    {
    'int64': 32,
    'float': 32,
    'varchar': '32',
    'json': {
    'key_32': 'value_32',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
    '32',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 32,
},
    {
    'int64': 33,
    'float': 33,
    'varchar': '33',
    'json': {
    'key_33': 'value_33',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
    '33',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 33,
},
    {
    'int64': 34,
    'float': 34,
    'varchar': '34',
    'json': {
    'key_34': 'value_34',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
    '34',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 34,
},
    {
    'int64': 35,
    'float': 35,
    'varchar': '35',
    'json': {
    'key_35': 'value_35',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
    '35',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 35,
},
    {
    'int64': 36,
    'float': 36,
    'varchar': '36',
    'json': {
    'key_36': 'value_36',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
    '36',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 36,
},
    {
    'int64': 37,
    'float': 37,
    'varchar': '37',
    'json': {
    'key_37': 'value_37',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
    '37',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 37,
},
    {
    'int64': 38,
    'float': 38,
    'varchar': '38',
    'json': {
    'key_38': 'value_38',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
    '38',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 38,
},
    {
    'int64': 39,
    'float': 39,
    'varchar': '39',
    'json': {
    'key_39': 'value_39',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
    '39',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 39,
},
    {
    'int64': 40,
    'float': 40,
    'varchar': '40',
    'json': {
    'key_40': 'value_40',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
    '40',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 40,
},
    {
    'int64': 41,
    'float': 41,
    'varchar': '41',
    'json': {
    'key_41': 'value_41',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
    '41',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 41,
},
    {
    'int64': 42,
    'float': 42,
    'varchar': '42',
    'json': {
    'key_42': 'value_42',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
    '42',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 42,
},
    {
    'int64': 43,
    'float': 43,
    'varchar': '43',
    'json': {
    'key_43': 'value_43',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
    '43',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 43,
},
    {
    'int64': 44,
    'float': 44,
    'varchar': '44',
    'json': {
    'key_44': 'value_44',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
    '44',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 44,
},
    {
    'int64': 45,
    'float': 45,
    'varchar': '45',
    'json': {
    'key_45': 'value_45',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
    '45',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 45,
},
    {
    'int64': 46,
    'float': 46,
    'varchar': '46',
    'json': {
    'key_46': 'value_46',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
    '46',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 46,
},
    {
    'int64': 47,
    'float': 47,
    'varchar': '47',
    'json': {
    'key_47': 'value_47',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
    '47',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 47,
},
    {
    'int64': 48,
    'float': 48,
    'varchar': '48',
    'json': {
    'key_48': 'value_48',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
    '48',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 48,
},
    {
    'int64': 49,
    'float': 49,
    'varchar': '49',
    'json': {
    'key_49': 'value_49',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
    '49',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 49,
},
    {
    'int64': 50,
    'float': 50,
    'varchar': '50',
    'json': {
    'key_50': 'value_50',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
    '50',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 50,
},
    {
    'int64': 51,
    'float': 51,
    'varchar': '51',
    'json': {
    'key_51': 'value_51',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
    '51',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 51,
},
    {
    'int64': 52,
    'float': 52,
    'varchar': '52',
    'json': {
    'key_52': 'value_52',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
    '52',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 52,
},
    {
    'int64': 53,
    'float': 53,
    'varchar': '53',
    'json': {
    'key_53': 'value_53',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
    '53',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 53,
},
    {
    'int64': 54,
    'float': 54,
    'varchar': '54',
    'json': {
    'key_54': 'value_54',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
    '54',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 54,
},
    {
    'int64': 55,
    'float': 55,
    'varchar': '55',
    'json': {
    'key_55': 'value_55',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
    '55',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 55,
},
    {
    'int64': 56,
    'float': 56,
    'varchar': '56',
    'json': {
    'key_56': 'value_56',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
    '56',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 56,
},
    {
    'int64': 57,
    'float': 57,
    'varchar': '57',
    'json': {
    'key_57': 'value_57',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
    '57',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 57,
},
    {
    'int64': 58,
    'float': 58,
    'varchar': '58',
    'json': {
    'key_58': 'value_58',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
    '58',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 58,
},
    {
    'int64': 59,
    'float': 59,
    'varchar': '59',
    'json': {
    'key_59': 'value_59',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
    '59',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 59,
},
    {
    'int64': 60,
    'float': 60,
    'varchar': '60',
    'json': {
    'key_60': 'value_60',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
    '60',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 60,
},
    {
    'int64': 61,
    'float': 61,
    'varchar': '61',
    'json': {
    'key_61': 'value_61',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
    '61',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 61,
},
    {
    'int64': 62,
    'float': 62,
    'varchar': '62',
    'json': {
    'key_62': 'value_62',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
    '62',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 62,
},
    {
    'int64': 63,
    'float': 63,
    'varchar': '63',
    'json': {
    'key_63': 'value_63',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
    '63',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 63,
},
    {
    'int64': 64,
    'float': 64,
    'varchar': '64',
    'json': {
    'key_64': 'value_64',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
    '64',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 64,
},
    {
    'int64': 65,
    'float': 65,
    'varchar': '65',
    'json': {
    'key_65': 'value_65',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
    '65',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 65,
},
    {
    'int64': 66,
    'float': 66,
    'varchar': '66',
    'json': {
    'key_66': 'value_66',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
    '66',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 66,
},
    {
    'int64': 67,
    'float': 67,
    'varchar': '67',
    'json': {
    'key_67': 'value_67',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
    '67',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 67,
},
    {
    'int64': 68,
    'float': 68,
    'varchar': '68',
    'json': {
    'key_68': 'value_68',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
    '68',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 68,
},
    {
    'int64': 69,
    'float': 69,
    'varchar': '69',
    'json': {
    'key_69': 'value_69',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
    '69',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 69,
},
    {
    'int64': 70,
    'float': 70,
    'varchar': '70',
    'json': {
    'key_70': 'value_70',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
    '70',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 70,
},
    {
    'int64': 71,
    'float': 71,
    'varchar': '71',
    'json': {
    'key_71': 'value_71',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
    '71',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 71,
},
    {
    'int64': 72,
    'float': 72,
    'varchar': '72',
    'json': {
    'key_72': 'value_72',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
    '72',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 72,
},
    {
    'int64': 73,
    'float': 73,
    'varchar': '73',
    'json': {
    'key_73': 'value_73',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
    '73',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 73,
},
    {
    'int64': 74,
    'float': 74,
    'varchar': '74',
    'json': {
    'key_74': 'value_74',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
    '74',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 74,
},
    {
    'int64': 75,
    'float': 75,
    'varchar': '75',
    'json': {
    'key_75': 'value_75',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
    '75',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 75,
},
    {
    'int64': 76,
    'float': 76,
    'varchar': '76',
    'json': {
    'key_76': 'value_76',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
    '76',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 76,
},
    {
    'int64': 77,
    'float': 77,
    'varchar': '77',
    'json': {
    'key_77': 'value_77',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
    '77',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 77,
},
    {
    'int64': 78,
    'float': 78,
    'varchar': '78',
    'json': {
    'key_78': 'value_78',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
    '78',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 78,
},
    {
    'int64': 79,
    'float': 79,
    'varchar': '79',
    'json': {
    'key_79': 'value_79',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
    '79',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 79,
},
    {
    'int64': 80,
    'float': 80,
    'varchar': '80',
    'json': {
    'key_80': 'value_80',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
    '80',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 80,
},
    {
    'int64': 81,
    'float': 81,
    'varchar': '81',
    'json': {
    'key_81': 'value_81',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
    '81',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 81,
},
    {
    'int64': 82,
    'float': 82,
    'varchar': '82',
    'json': {
    'key_82': 'value_82',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
    '82',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 82,
},
    {
    'int64': 83,
    'float': 83,
    'varchar': '83',
    'json': {
    'key_83': 'value_83',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
    '83',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 83,
},
    {
    'int64': 84,
    'float': 84,
    'varchar': '84',
    'json': {
    'key_84': 'value_84',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
    '84',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 84,
},
    {
    'int64': 85,
    'float': 85,
    'varchar': '85',
    'json': {
    'key_85': 'value_85',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
    '85',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 85,
},
    {
    'int64': 86,
    'float': 86,
    'varchar': '86',
    'json': {
    'key_86': 'value_86',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
    '86',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 86,
},
    {
    'int64': 87,
    'float': 87,
    'varchar': '87',
    'json': {
    'key_87': 'value_87',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
    '87',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 87,
},
    {
    'int64': 88,
    'float': 88,
    'varchar': '88',
    'json': {
    'key_88': 'value_88',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
    '88',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 88,
},
    {
    'int64': 89,
    'float': 89,
    'varchar': '89',
    'json': {
    'key_89': 'value_89',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
    '89',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 89,
},
    {
    'int64': 90,
    'float': 90,
    'varchar': '90',
    'json': {
    'key_90': 'value_90',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
    '90',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 90,
},
    {
    'int64': 91,
    'float': 91,
    'varchar': '91',
    'json': {
    'key_91': 'value_91',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
    '91',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 91,
},
    {
    'int64': 92,
    'float': 92,
    'varchar': '92',
    'json': {
    'key_92': 'value_92',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
    '92',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 92,
},
    {
    'int64': 93,
    'float': 93,
    'varchar': '93',
    'json': {
    'key_93': 'value_93',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
    '93',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 93,
},
    {
    'int64': 94,
    'float': 94,
    'varchar': '94',
    'json': {
    'key_94': 'value_94',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
    '94',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 94,
},
    {
    'int64': 95,
    'float': 95,
    'varchar': '95',
    'json': {
    'key_95': 'value_95',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
    '95',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 95,
},
    {
    'int64': 96,
    'float': 96,
    'varchar': '96',
    'json': {
    'key_96': 'value_96',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
    '96',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 96,
},
    {
    'int64': 97,
    'float': 97,
    'varchar': '97',
    'json': {
    'key_97': 'value_97',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
    '97',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 97,
},
    {
    'int64': 98,
    'float': 98,
    'varchar': '98',
    'json': {
    'key_98': 'value_98',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
    '98',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 98,
},
    {
    'int64': 99,
    'float': 99,
    'varchar': '99',
    'json': {
    'key_99': 'value_99',
},
    'int_array': self.mutator.generate_float_array(dimension=10, normalized=True),
    'varchar_array': [
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
    '99',
],
    'float_vector': self.mutator.generate_float_array(dimension=128, normalized=True),
    'age': 99,
},
],
}


        send_request(original_content, method, url_path, headers)
        return True



# 主函数
if __name__ == "__main__":
    # 解析命令行参数
    parser = argparse.ArgumentParser(description='VDB模糊测试 - allmilvus_log.TestRestfulSdkCompatibility_test_collection_create_by_sdk_insert_vector_by_restful_1752747033.json')
    parser.add_argument('-t', '--target', type=str, default=TARGET_URL,
                        help='目标服务器URL，例如: http://localhost:6333')
    parser.add_argument('-o', '--output-dir', type=str, default=OUTPUT_DIR,
                        help='测试结果输出目录')
    parser.add_argument('-n', '--iterations', type=int, default=200,
                        help='变异测试的最大迭代次数')
    parser.add_argument('-l', '--time-limit', type=int, default=10,
                        help='变异测试的时间限制(分钟)')
    args = parser.parse_args()
    
    # 更新全局变量
    if args.target:
        TARGET_URL = args.target
    if args.output_dir:
        OUTPUT_DIR = args.output_dir
    
    # 创建输出目录
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 实例化测试类并运行测试
    test = AllmilvusLogtestrestfulsdkcompatibilityTestCollectionCreateBySdkInsertVectorByRestful1752747033Json()
    test.run_tests()
